// Server-side copy of the hint prompt. Lives in lib/ (shared by the Vercel
// functions and the Vite dev middleware) because the GPT-Live engine has
// no out-of-band text channel: hints are generated by a normal chat
// completion on the server from the recent transcript instead of by the
// voice model itself. src/lib/realtime.ts keeps its own copy for the
// Realtime engine; delete that one when the Realtime path is retired.

/// Hint prompt — mirrors the iOS hintInstructions exactly so the two
/// platforms produce comparable output. Output rules are spelled out
/// multiple ways because models sometimes obey only one phrasing.
///
/// Exported for unit testing — the prompt content materially affects
/// what users see in the hint panel, so we verify it directly.
export function buildHintInstructions(
  proficiency: string,
  languageLabel: string,
  nativeLanguage: string,
): string {
  const outputRules = `OUTPUT RULES (STRICT — the UI already shows a "Try saying…" header above your output):
- Output ONLY the phrases. Nothing else.
- NO preamble line ("Here are some ideas", "Algumas ideias para continuar", "Voici quelques idées", etc.). Skip directly to the phrases.
- NO numbering, bullets, asterisks, or markdown.
- NO closing remark.
- One phrase per line. That is the entire response.`

  switch (proficiency) {
    case 'first_timer':
    case 'complete-beginner':
      return `The learner is paused, looking for something to say. They are a TRUE BEGINNER in ${languageLabel} and know virtually no ${languageLabel}.
Give them 2 short, useful ${languageLabel} phrases they could say RIGHT NOW based on the current conversation context.
Each phrase MUST include a ${nativeLanguage} translation in parentheses.

${outputRules}

Example output (exact format, nothing else):
Oi! (Hi)
Tudo bem? (How are you?)`
    case 'basic':
    case 'novice':
      return `The learner is paused. They are a BASIC ${languageLabel} learner who knows greetings and a few short phrases.
Give them 2 short ${languageLabel} phrases or sentence starters they could use right now, with brief ${nativeLanguage} hints in parens.

${outputRules}`
    case 'intermediate':
    case 'advanced':
      return `The learner is paused — not because they lack vocabulary but because they're stuck for ideas.
Give them 2 conversational nudges or sentence starters in ${languageLabel} they could use right now. They do NOT need translations.

${outputRules}

Examples of the right shape (these are the phrases themselves — no preamble before them):
"Você poderia perguntar sobre o trabalho dela"
"Try 'Eu acho que…' to share your opinion"`
    default:
      return `The learner is paused. Give them 2 short ${languageLabel} phrases they could say right now, with brief ${nativeLanguage} hints in parens.

${outputRules}`
  }
}
