// Auto-converted from iOS WalkieTalkie/Models/LessonContent_German.swift.
// Update the iOS source first, then re-run the conversion script. See
// LessonCatalog for the lookup pipeline.

import type { LessonPhrase } from '../types'

export const germanPhrases: Record<string, LessonPhrase[]> = {


        // First Timer

        "ft-1-1": [
            { target: "Hi!", native: "Hi!" },
            { target: "Hallo, wie geht's?", native: "Hello, how are you?" },
            { target: "Gut, und dir?", native: "I'm good, and you?" },
            { target: "Guten Morgen", native: "Good morning" },
            { target: "Guten Abend", native: "Good evening / Goodnight" },
        ],
        "ft-1-2": [
            { target: "Ich heiße …", native: "My name is …" },
            { target: "Freut mich, dich kennenzulernen", native: "Nice to meet you" },
            { target: "Wie heißt du?", native: "What's your name?" },
            { target: "Ich komme aus den USA", native: "I'm from the United States" },
            { target: "Bist du von hier?", native: "Are you from here?" },
        ],
        "ft-1-3": [
            { target: "Ich wohne in …", native: "I live in …" },
            { target: "Ich komme aus …", native: "I'm from …" },
            { target: "Es ist eine große Stadt", native: "It's a big city" },
            { target: "Es liegt in der Nähe von …", native: "It's near …" },
            { target: "Warst du schon mal dort?", native: "Have you been there?" },
        ],
        "ft-2-1": [
            { target: "Einen Kaffee, bitte", native: "A coffee, please" },
            { target: "Mit Milch", native: "With milk" },
            { target: "Zum Mitnehmen", native: "To go" },
            { target: "Was kostet das?", native: "How much is it?" },
            { target: "Danke", native: "Thank you" },
        ],
        "ft-2-2": [
            { target: "Wie viel kostet das?", native: "How much is this?" },
            { target: "Das ist zu teuer", native: "It's too expensive" },
            { target: "Nehmen Sie Karte?", native: "Do you take card?" },
            { target: "In bar", native: "In cash" },
            { target: "Kann ich bitte die Quittung haben?", native: "Can I get the receipt?" },
        ],
        "ft-2-3": [
            { target: "Vielen Dank", native: "Thanks a lot" },
            { target: "Gern geschehen", native: "You're welcome" },
            { target: "Bis bald", native: "See you soon" },
            { target: "Tschüss", native: "Bye" },
            { target: "Es war mir eine Freude", native: "It was a pleasure" },
        ],
        "ft-3-1": [
            { target: "Zum Flughafen, bitte", native: "To the airport, please" },
            { target: "Wie lange dauert das?", native: "How long does it take?" },
            { target: "Können Sie bitte langsamer fahren?", native: "Can you slow down?" },
            { target: "Hier ist gut", native: "Here is fine" },
            { target: "Was schulde ich Ihnen?", native: "How much do I owe you?" },
        ],
        "ft-3-2": [
            { target: "Wie komme ich zur …?", native: "How do I get to the …?" },
            { target: "Ist das weit von hier?", native: "Is it far from here?" },
            { target: "Biegen Sie links ab", native: "Turn left" },
            { target: "Gehen Sie geradeaus", native: "Go straight" },
            { target: "Danke für die Hilfe", native: "Thanks for your help" },
        ],
        "ft-3-3": [
            { target: "Ich habe das nicht verstanden", native: "I didn't understand" },
            { target: "Kannst du das wiederholen?", native: "Can you repeat?" },
            { target: "Langsamer, bitte", native: "Slower, please" },
            { target: "Wie sagt man … auf Deutsch?", native: "How do you say …?" },
            { target: "Sprichst du Englisch?", native: "Do you speak English?" },
        ],
        "ft-4-1": [
            { target: "Sehr erfreut", native: "Very nice to meet you" },
            { target: "Was für ein schönes Zuhause", native: "What a beautiful home" },
            { target: "Danke für die Einladung", native: "Thanks for the invitation" },
            { target: "Kann ich helfen?", native: "Can I help?" },
            { target: "Es hat super geschmeckt", native: "It was delicious" },
        ],
        "ft-4-2": [
            { target: "Was für ein schönes Wetter heute", native: "What lovely weather today" },
            { target: "Bist du von hier?", native: "Are you from here?" },
            { target: "Gefällt dir Deutschland?", native: "Are you enjoying it here?" },
            { target: "Was machst du so?", native: "What do you do?" },
            { target: "Man sieht sich", native: "See you around" },
        ],
        "ft-4-3": [
            { target: "Ich arbeite im Bereich …", native: "I work in/with …" },
            { target: "Ich bin … von Beruf", native: "I'm a … by profession" },
            { target: "Ich arbeite von zu Hause", native: "I work from home" },
            { target: "Ich liebe, was ich mache", native: "I love what I do" },
            { target: "Und du, was machst du beruflich?", native: "And you, what do you do?" },
        ],

        // Basic

        "b-1-1": [
            { target: "Ich suche ein Geschenk", native: "I'm looking for a gift" },
            { target: "Es ist für einen Freund", native: "It's for a friend" },
            { target: "Haben Sie etwas Typisches?", native: "Do you have something typical?" },
            { target: "Was kostet das hier?", native: "How much is that one?" },
            { target: "Das nehme ich", native: "I'll take it" },
        ],
        "b-1-2": [
            { target: "Kann ich das mal anprobieren?", native: "Can I try it on?" },
            { target: "Haben Sie eine andere Größe?", native: "Do you have another size?" },
            { target: "Es sitzt ein bisschen eng", native: "It's a bit tight" },
            { target: "Diese Farbe gefällt mir richtig gut", native: "I love this color" },
            { target: "Steht es mir?", native: "Does it look good on me?" },
        ],
        "b-1-3": [
            { target: "Ein Kilo Tomaten, bitte", native: "A kilo of tomatoes, please" },
            { target: "Sind die reif?", native: "Are they ripe?" },
            { target: "Können Sie mir die besten raussuchen?", native: "Can you pick the best ones?" },
            { target: "Haben die gerade Saison?", native: "Is it in season?" },
            { target: "Sonst noch etwas? Nein, das war's", native: "Anything else? No, that's it" },
        ],
        "b-2-1": [
            { target: "Ich liebe …", native: "I love …" },
            { target: "Ich esse kein Fleisch", native: "I don't eat meat" },
            { target: "Ich bin allergisch gegen …", native: "I'm allergic to …" },
            { target: "Was ist dein Lieblingsgericht?", native: "What's your favorite dish?" },
            { target: "Kochst du gerne?", native: "Do you cook?" },
        ],
        "b-2-2": [
            { target: "Mein Lieblingsfilm ist …", native: "My favorite movie is …" },
            { target: "Es geht um …", native: "It's about …" },
            { target: "Hast du den schon gesehen?", native: "Have you seen it?" },
            { target: "Der war wirklich bewegend", native: "It was really moving" },
            { target: "Ich kann ihn nur empfehlen", native: "I recommend it" },
        ],
        "b-2-3": [
            { target: "In meiner Freizeit …", native: "In my free time I …" },
            { target: "Ich mache das seit … Jahren", native: "I've been doing it for … years" },
            { target: "Das ist total entspannend", native: "It's very relaxing" },
            { target: "Hast du irgendwelche Hobbys?", native: "Do you have any hobbies?" },
            { target: "Ich kann's dir mal zeigen", native: "I can teach you" },
        ],
        "b-3-1": [
            { target: "Meine Familie wohnt in …", native: "My family lives in …" },
            { target: "Meine Eltern kommen aus …", native: "My parents are from …" },
            { target: "Ich habe einen jüngeren Bruder", native: "I have a younger brother" },
            { target: "Ich sehe sie an den Feiertagen", native: "I see them on holidays" },
            { target: "Sie fehlen mir", native: "I miss them" },
        ],
        "b-3-2": [
            { target: "Wir sind vier in der Familie", native: "There are four of us" },
            { target: "Mein Bruder ist älter", native: "My brother is older" },
            { target: "Meine Mutter ist Lehrerin", native: "My mom is a teacher" },
            { target: "Wir sind sehr eng verbunden", native: "We're very close" },
            { target: "Hast du Fotos? Darf ich mal sehen?", native: "Got photos? Can I see?" },
        ],
        "b-3-3": [
            { target: "Am Wochenende machen wir meistens …", native: "On weekends we usually …" },
            { target: "Wir essen immer zusammen zu Abend", native: "We always eat dinner together" },
            { target: "Wir feiern Weihnachten zusammen", native: "We celebrate at Christmas" },
            { target: "Meine Oma kocht das Essen", native: "My grandma cooks the food" },
            { target: "Das ist eine Familientradition", native: "It's a family tradition" },
        ],
        "b-4-1": [
            { target: "Ich komme am Dienstag an", native: "I arrive on Tuesday" },
            { target: "Ich bleibe eine Woche", native: "I'm staying a week" },
            { target: "Ich möchte … sehen", native: "I want to see …" },
            { target: "Was kannst du empfehlen?", native: "What do you recommend?" },
            { target: "Ich miete ein Auto", native: "I'm renting a car" },
        ],
        "b-4-2": [
            { target: "Ich stehe um sieben auf", native: "I wake up at seven" },
            { target: "Ich arbeite bis sechs", native: "I work until six" },
            { target: "Nachmittags gehe ich ins Fitnessstudio", native: "In the afternoon I have gym" },
            { target: "Ich esse zu Hause zu Abend", native: "I have dinner at home" },
            { target: "Ich gehe früh ins Bett", native: "I sleep early" },
        ],
        "b-4-3": [
            { target: "Hast du Lust, am Freitag was zu machen?", native: "Do you want to go out Friday?" },
            { target: "Gibt's hier irgendwo was Cooles?", native: "Is there somewhere cool?" },
            { target: "Um wie viel Uhr treffen wir uns?", native: "What time do we meet?" },
            { target: "Abgemacht!", native: "Deal!" },
            { target: "Ich schreibe dir auf WhatsApp", native: "I'll text you on WhatsApp" },
        ],

        // Intermediate

        "i-1-1": [
            { target: "Heute ist mir was Lustiges passiert", native: "Something funny happened today" },
            { target: "Ich war mitten in einem Meeting, als …", native: "I was in the middle of a meeting when …" },
            { target: "Am Ende hat alles geklappt", native: "In the end everything worked out" },
            { target: "Es war stressig, aber es hat sich gelohnt", native: "It was stressful but it was worth it" },
            { target: "Kannst du das glauben?", native: "Can you believe that?" },
        ],
        "i-1-2": [
            { target: "Für mich, …", native: "For me, …" },
            { target: "Ehrlich gesagt finde ich, dass …", native: "Honestly, I think that …" },
            { target: "Ich bin mir nicht sicher, aber …", native: "I'm not sure, but …" },
            { target: "Der Hauptgrund ist …", native: "The main reason is …" },
            { target: "Lass uns einfach unterschiedlicher Meinung sein", native: "Let's agree to disagree" },
        ],
        "i-1-3": [
            { target: "Ich verstehe deinen Punkt, aber …", native: "I see your point, but …" },
            { target: "Ich stimme bis zu einem gewissen Grad zu", native: "I agree up to a point" },
            { target: "Aus meiner Sicht, …", native: "From my perspective, …" },
            { target: "Wäre es nicht doch besser, …?", native: "Wouldn't it be better to …?" },
            { target: "Was du sagst, ergibt Sinn", native: "What you're saying makes sense" },
        ],
        "i-2-1": [
            { target: "Entschuldigung, kann ich kurz mit Ihnen sprechen?", native: "Excuse me, can I speak with you?" },
            { target: "Es gibt ein Problem mit …", native: "There's a problem with …" },
            { target: "Lässt sich das irgendwie lösen?", native: "Is there any way to fix it?" },
            { target: "Ich bin damit nicht zufrieden", native: "I'm not satisfied" },
            { target: "Danke für Ihre Aufmerksamkeit", native: "Thanks for the attention" },
        ],
        "i-2-2": [
            { target: "Tut mir leid, dass ich zu spät bin", native: "Sorry I'm late" },
            { target: "Es ist mir etwas dazwischengekommen", native: "Something unexpected came up" },
            { target: "Der Verkehr war echt furchtbar", native: "The traffic was terrible" },
            { target: "Das wird nicht wieder vorkommen", native: "It won't happen again" },
            { target: "Kann ich das irgendwie wiedergutmachen?", native: "Can I make it up to you?" },
        ],
        "i-2-3": [
            { target: "Das ist mir ein bisschen zu teuer", native: "It's a bit expensive for me" },
            { target: "Geht da was am Preis?", native: "Could you do it for less?" },
            { target: "Wenn ich zwei nehme, gibt's dann Rabatt?", native: "If I take two, can I get a discount?" },
            { target: "Was ist Ihr bester Preis?", native: "What's the best price?" },
            { target: "Abgemacht, ich nehme es", native: "Deal, I'll take it" },
        ],
        "i-3-1": [
            { target: "In fünf Jahren hoffe ich, …", native: "In five years, I hope to …" },
            { target: "Mein Plan ist, …", native: "My plan is …" },
            { target: "Ich arbeite gerade darauf hin, …", native: "I'm working toward …" },
            { target: "Wenn alles gut läuft, …", native: "If all goes well, …" },
            { target: "Ich weiß es halt noch nicht so genau", native: "I'm not entirely sure yet" },
        ],
        "i-3-2": [
            { target: "Ich arbeite gerade an einem Projekt, das …", native: "I'm working on a project that …" },
            { target: "Meine Rolle ist …", native: "My role is …" },
            { target: "Das Schwierigste daran ist …", native: "The hardest part is …" },
            { target: "Ich habe viel dabei gelernt", native: "I've learned a lot from it" },
            { target: "Die Deadline ist ziemlich knapp", native: "The deadline is tight" },
        ],
        "i-3-3": [
            { target: "Darf ich dir mal einen Vorschlag machen?", native: "Can I give you a suggestion?" },
            { target: "An deiner Stelle würde ich …", native: "If I were you, …" },
            { target: "Hast du schon mal überlegt, …?", native: "Have you thought about …?" },
            { target: "Sei doch nicht so streng mit dir selbst", native: "Try not to be so hard on yourself" },
            { target: "Das wird schon alles gut", native: "Everything will work out" },
        ],
        "i-4-1": [
            { target: "Bei uns zu Hause machen wir das normalerweise so: …", native: "Back in my country, we usually …" },
            { target: "Hier ist es schon anders, weil …", native: "Here it's quite different because …" },
            { target: "Was mir besonders aufgefallen ist, war …", native: "One thing that struck me was …" },
            { target: "Ich finde es so, wie es hier gemacht wird, besser", native: "I prefer the way it's done here" },
            { target: "Jeder Ort hat halt seinen eigenen Charme", native: "Every place has its charm" },
        ],
        "i-4-2": [
            { target: "Es war eine unvergessliche Reise", native: "It was an unforgettable trip" },
            { target: "Was mich am meisten beeindruckt hat, war …", native: "What struck me most was …" },
            { target: "Ich habe großartige Menschen kennengelernt", native: "I met amazing people" },
            { target: "Ich bin als ein anderer Mensch zurückgekommen", native: "I came back a different person" },
            { target: "Ich kann es nur wärmstens empfehlen", native: "I highly recommend it" },
        ],
        "i-4-3": [
            { target: "Du musst unbedingt nach … gehen", native: "You have to go to …" },
            { target: "Das ist ein Ort, der für mich eine ganz besondere Geschichte hat", native: "It's a place with a special story for me" },
            { target: "Das wird dir bestimmt gefallen", native: "You'll definitely like it" },
            { target: "Geh lieber nicht am Wochenende hin", native: "Avoid going on weekends" },
            { target: "Erzähl mir danach, wie du es fandest", native: "Tell me later what you thought" },
        ],

        // Advanced

        "a-1-1": [
            { target: "Meiner Meinung nach lohnt sich Homeoffice deutlich mehr", native: "In my opinion, remote work is much more worth it" },
            { target: "Das Büro hat ja schon seine Vorteile, aber …", native: "The office has its advantages, but …" },
            { target: "Genau deswegen sehe ich das anders", native: "I disagree precisely because of that" },
            { target: "Du vergisst dabei aber ein wichtiges Detail", native: "You're forgetting an important detail" },
            { target: "Letzten Endes hängt es halt stark von der Art der Arbeit ab", native: "At the end of the day, it depends a lot on the type of work" },
        ],
        "a-1-2": [
            { target: "Ich weiß, dass die meisten das anders sehen, aber …", native: "I know most people think otherwise, but …" },
            { target: "Ich glaube, das wird oft falsch verstanden", native: "I think this is misunderstood" },
            { target: "Das Standardargument dagegen lautet …, aber …", native: "The standard argument against this is …, but …" },
            { target: "Ich vertrete diese Meinung, weil …", native: "I hold this opinion because …" },
            { target: "Ich kann ja auch falsch liegen, aber …", native: "I might even be wrong, but …" },
        ],
        "a-1-3": [
            { target: "Es gibt gerade eine riesige Debatte über …", native: "There's a huge debate going on about …" },
            { target: "Worum es im Kern geht, ist …", native: "What's at stake is …" },
            { target: "Ich stelle mich auf die Seite von …", native: "I side with …" },
            { target: "Das ist eine komplexe Frage, da gibt es keine einfache Antwort", native: "It's a complex issue, there's no easy answer" },
            { target: "Das spaltet sogar innerhalb meiner Familie die Meinungen", native: "This divides opinions even within my family" },
        ],
        "a-2-1": [
            { target: "Du wirst nicht glauben, was passiert ist", native: "You won't believe what happened" },
            { target: "Angefangen hat alles, als …", native: "It all started when …" },
            { target: "Und dann, aus dem Nichts, …", native: "Then, out of nowhere, …" },
            { target: "Um es kurz zu machen, …", native: "To cut a long story short, …" },
            { target: "Ich muss heute noch lachen, wenn ich daran denke", native: "I still laugh when I remember this" },
        ],
        "a-2-2": [
            { target: "Vorher dachte ich immer, dass …", native: "Before this, I used to think that …" },
            { target: "Da hat sich dann alles geändert", native: "That's when everything changed" },
            { target: "Das hat mich die Dinge in einem ganz anderen Licht sehen lassen", native: "That made me see things differently" },
            { target: "Heute sehe ich das völlig anders", native: "Nowadays, I see this in a completely different way" },
            { target: "Das war für mich ein echter Wendepunkt", native: "It was a watershed moment for me" },
        ],
        "a-2-3": [
            { target: "Das ist einer von denen, die einem noch lange im Kopf bleiben", native: "It's one of those that sticks with you long after" },
            { target: "Was mich am meisten beeindruckt hat, war …", native: "What struck me most was …" },
            { target: "Es gibt eine bestimmte Szene, die allein schon den Film wert ist", native: "There's one specific scene that's worth it on its own" },
            { target: "Ich kann ihn bedenkenlos empfehlen", native: "I recommend it without hesitation" },
            { target: "Hat dich das an etwas Ähnliches in deinem Leben erinnert?", native: "Did it make you think of something similar in your own life?" },
        ],
        "a-3-1": [
            { target: "Ganz grob zusammengefasst, …", native: "Putting it really roughly, …" },
            { target: "Damit du eine Vorstellung bekommst, …", native: "To give you an idea, …" },
            { target: "Im Alltag geht es viel um …", native: "The day-to-day involves a lot of …" },
            { target: "Das Schwierigste ist ohne Frage …", native: "The hardest part is, without a doubt, …" },
            { target: "Ergibt das so, wie ich es erkläre, Sinn?", native: "Does what I'm explaining make sense?" },
        ],
        "a-3-2": [
            { target: "Pass mal auf, ich erkläre dir kurz, warum das gerade jetzt Sinn ergibt", native: "Look, let me tell you why this makes sense right now" },
            { target: "Was uns von anderen unterscheidet, ist …", native: "What sets us apart is …" },
            { target: "Warum gerade ich? Weil ich dieses Problem am eigenen Leib erlebt habe", native: "Why me? Because I've lived this problem firsthand" },
            { target: "Ich glaube fest daran, weil …", native: "I really believe in this because …" },
            { target: "Ich wette, ganz viele Leute brauchen genau das", native: "I bet a lot of people need exactly this" },
        ],
        "a-3-3": [
            { target: "Ich verstehe deinen Punkt, aber ich muss da widersprechen", native: "I understand your point, but I'm going to disagree" },
            { target: "Du hast zum Teil recht, allerdings …", native: "You're partly right, however …" },
            { target: "Darf ich dir mal eine andere Perspektive anbieten?", native: "Can I offer you another perspective?" },
            { target: "Vielleicht schauen wir das einfach aus verschiedenen Blickwinkeln an", native: "Maybe we're looking at this from different angles" },
            { target: "Im Grunde wollen wir, glaube ich, dasselbe, nur auf unterschiedlichen Wegen", native: "Deep down, I think we want the same thing, just by different paths" },
        ],
        "a-4-1": [
            { target: "Ein Unterschied, der mir auffällt, ist …", native: "One difference that strikes me is …" },
            { target: "Bei uns zu Hause neigen wir dazu, …, während hier …", native: "Back in my country, we tend to …, while here …" },
            { target: "Jede Kultur hat halt ihren eigenen Umgang damit", native: "Each culture has its own way of dealing with this" },
            { target: "Ich glaube, wir könnten viel von … lernen", native: "I think we could learn a lot from …" },
            { target: "Es ist weder besser noch schlechter, einfach anders", native: "It's not better or worse, it's different" },
        ],
        "a-4-2": [
            { target: "Eine Sache, die sich stark verändert hat, ist …", native: "One thing that's changed a lot is …" },
            { target: "Früher war es so, heute ist es komplett anders", native: "It used to be one way, now it's completely different" },
            { target: "Ich weiß nicht, ob das zum Besseren oder zum Schlechteren ist", native: "I don't know if it's for better or worse" },
            { target: "Das spiegelt einen größeren Wandel in der Gesellschaft wider", native: "This reflects a bigger shift in society" },
            { target: "Ich habe das Gefühl, wir leben gerade in einer Umbruchphase", native: "I feel like we're living through a moment of transition" },
        ],
        "a-4-3": [
            { target: "Was ich gerade am meisten konsumiere, ist …", native: "What I consume most right now is …" },
            { target: "Ich glaube, das sagt viel über mich aus, weil …", native: "I think this says a lot about me because …" },
            { target: "Ich kann nicht lange ohne … auskommen", native: "I can't go too long without …" },
            { target: "Ich versuche, leichten Stoff mit anspruchsvolleren Sachen auszubalancieren", native: "I try to balance lighter content with denser stuff" },
            { target: "Hast du irgendeine Empfehlung für mich?", native: "Got any recommendations for me?" },
        ],
}
