// Auto-converted from iOS WalkieTalkie/Models/LessonContent_Spanish.swift.
// Update the iOS source first, then re-run the conversion script. See
// LessonCatalog for the lookup pipeline.

import type { LessonPhrase } from '../types'

export const spanishPhrases: Record<string, LessonPhrase[]> = {


        // First Timer

        "ft-1-1": [
            { target: "¡Hola!", native: "Hi!" },
            { target: "Hola, ¿cómo estás?", native: "Hello, how are you?" },
            { target: "Bien, ¿y tú?", native: "I'm good, and you?" },
            { target: "Buenos días", native: "Good morning" },
            { target: "Buenas noches", native: "Good evening / Goodnight" },
        ],
        "ft-1-2": [
            { target: "Me llamo …", native: "My name is …" },
            { target: "Mucho gusto", native: "Nice to meet you" },
            { target: "¿Cómo te llamas?", native: "What's your name?" },
            { target: "Soy de Estados Unidos", native: "I'm from the United States" },
            { target: "¿Eres de aquí?", native: "Are you from here?" },
        ],
        "ft-1-3": [
            { target: "Vivo en …", native: "I live in …" },
            { target: "Soy de …", native: "I'm from …" },
            { target: "Es una ciudad grande", native: "It's a big city" },
            { target: "Queda cerca de …", native: "It's near …" },
            { target: "¿Ya has ido?", native: "Have you been there?" },
        ],
        "ft-2-1": [
            { target: "Un café, por favor", native: "A coffee, please" },
            { target: "Con leche", native: "With milk" },
            { target: "Para llevar", native: "To go" },
            { target: "¿Cuánto cuesta?", native: "How much is it?" },
            { target: "Gracias", native: "Thank you" },
        ],
        "ft-2-2": [
            { target: "¿Cuánto cuesta esto?", native: "How much is this?" },
            { target: "Está muy caro", native: "It's too expensive" },
            { target: "¿Aceptan tarjeta?", native: "Do you take card?" },
            { target: "En efectivo", native: "In cash" },
            { target: "¿Me da el recibo?", native: "Can I get the receipt?" },
        ],
        "ft-2-3": [
            { target: "Muchas gracias", native: "Thanks a lot" },
            { target: "De nada", native: "You're welcome" },
            { target: "Hasta luego", native: "See you soon" },
            { target: "Adiós", native: "Bye" },
            { target: "Fue un placer", native: "It was a pleasure" },
        ],
        "ft-3-1": [
            { target: "Al aeropuerto, por favor", native: "To the airport, please" },
            { target: "¿Cuánto tarda?", native: "How long does it take?" },
            { target: "¿Puede ir más despacio?", native: "Can you slow down?" },
            { target: "Aquí está bien", native: "Here is fine" },
            { target: "¿Cuánto le debo?", native: "How much do I owe you?" },
        ],
        "ft-3-2": [
            { target: "¿Cómo llego a …?", native: "How do I get to the …?" },
            { target: "¿Está lejos de aquí?", native: "Is it far from here?" },
            { target: "Da vuelta a la izquierda", native: "Turn left" },
            { target: "Sigue derecho", native: "Go straight" },
            { target: "Gracias por la ayuda", native: "Thanks for your help" },
        ],
        "ft-3-3": [
            { target: "No entendí", native: "I didn't understand" },
            { target: "¿Puede repetir?", native: "Can you repeat?" },
            { target: "Más despacio, por favor", native: "Slower, please" },
            { target: "¿Cómo se dice … en español?", native: "How do you say …?" },
            { target: "¿Hablas inglés?", native: "Do you speak English?" },
        ],
        "ft-4-1": [
            { target: "Mucho gusto", native: "Very nice to meet you" },
            { target: "Qué bonita casa", native: "What a beautiful home" },
            { target: "Gracias por la invitación", native: "Thanks for the invitation" },
            { target: "¿Te ayudo en algo?", native: "Can I help?" },
            { target: "Estaba delicioso", native: "It was delicious" },
        ],
        "ft-4-2": [
            { target: "Qué bonito clima hoy", native: "What lovely weather today" },
            { target: "¿Eres de aquí?", native: "Are you from here?" },
            { target: "¿Te está gustando México?", native: "Are you enjoying it here?" },
            { target: "¿A qué te dedicas?", native: "What do you do?" },
            { target: "Nos vemos por ahí", native: "See you around" },
        ],
        "ft-4-3": [
            { target: "Trabajo en …", native: "I work in/with …" },
            { target: "Soy … de profesión", native: "I'm a … by profession" },
            { target: "Trabajo desde casa", native: "I work from home" },
            { target: "Me encanta lo que hago", native: "I love what I do" },
            { target: "¿Y tú, a qué te dedicas?", native: "And you, what do you do?" },
        ],

        // Basic

        "b-1-1": [
            { target: "Estoy buscando un regalo", native: "I'm looking for a gift" },
            { target: "Es para un amigo", native: "It's for a friend" },
            { target: "¿Tiene algo típico de aquí?", native: "Do you have something typical?" },
            { target: "¿Cuánto cuesta ese?", native: "How much is that one?" },
            { target: "Me lo llevo", native: "I'll take it" },
        ],
        "b-1-2": [
            { target: "¿Me lo puedo probar?", native: "Can I try it on?" },
            { target: "¿Tiene otra talla?", native: "Do you have another size?" },
            { target: "Me queda un poco apretado", native: "It's a bit tight" },
            { target: "Me encanta este color", native: "I love this color" },
            { target: "¿Cómo me queda?", native: "Does it look good on me?" },
        ],
        "b-1-3": [
            { target: "Un kilo de jitomate, por favor", native: "A kilo of tomatoes, please" },
            { target: "¿Están maduros?", native: "Are they ripe?" },
            { target: "¿Me escoge los mejores?", native: "Can you pick the best ones?" },
            { target: "¿Es de temporada?", native: "Is it in season?" },
            { target: "¿Algo más? No, así está bien", native: "Anything else? No, that's it" },
        ],
        "b-2-1": [
            { target: "Me encanta …", native: "I love …" },
            { target: "No como carne", native: "I don't eat meat" },
            { target: "Soy alérgico a …", native: "I'm allergic to …" },
            { target: "¿Cuál es tu platillo favorito?", native: "What's your favorite dish?" },
            { target: "¿Tú cocinas?", native: "Do you cook?" },
        ],
        "b-2-2": [
            { target: "Mi película favorita es …", native: "My favorite movie is …" },
            { target: "Trata de …", native: "It's about …" },
            { target: "¿Ya la viste?", native: "Have you seen it?" },
            { target: "Fue muy emocionante", native: "It was really moving" },
            { target: "Te la recomiendo", native: "I recommend it" },
        ],
        "b-2-3": [
            { target: "En mi tiempo libre …", native: "In my free time I …" },
            { target: "Llevo … años haciéndolo", native: "I've been doing it for … years" },
            { target: "Es muy relajante", native: "It's very relaxing" },
            { target: "¿Tienes algún pasatiempo?", native: "Do you have any hobbies?" },
            { target: "Yo te puedo enseñar", native: "I can teach you" },
        ],
        "b-3-1": [
            { target: "Mi familia vive en …", native: "My family lives in …" },
            { target: "Mis papás son de …", native: "My parents are from …" },
            { target: "Tengo un hermano menor", native: "I have a younger brother" },
            { target: "Los veo en las vacaciones", native: "I see them on holidays" },
            { target: "Los extraño mucho", native: "I miss them" },
        ],
        "b-3-2": [
            { target: "Somos cuatro en la familia", native: "There are four of us" },
            { target: "Mi hermano es el mayor", native: "My brother is older" },
            { target: "Mi mamá es maestra", native: "My mom is a teacher" },
            { target: "Somos muy unidos", native: "We're very close" },
            { target: "¿Tienes fotos? ¿Me enseñas?", native: "Got photos? Can I see?" },
        ],
        "b-3-3": [
            { target: "Los fines de semana solemos …", native: "On weekends we usually …" },
            { target: "Siempre cenamos juntos", native: "We always eat dinner together" },
            { target: "Lo festejamos en Navidad", native: "We celebrate at Christmas" },
            { target: "Mi abuela hace la comida", native: "My grandma cooks the food" },
            { target: "Es una tradición familiar", native: "It's a family tradition" },
        ],
        "b-4-1": [
            { target: "Llego el martes", native: "I arrive on Tuesday" },
            { target: "Me voy a quedar una semana", native: "I'm staying a week" },
            { target: "Quiero conocer …", native: "I want to see …" },
            { target: "¿Qué me recomiendas?", native: "What do you recommend?" },
            { target: "Voy a rentar un carro", native: "I'm renting a car" },
        ],
        "b-4-2": [
            { target: "Me levanto a las siete", native: "I wake up at seven" },
            { target: "Trabajo hasta las seis", native: "I work until six" },
            { target: "En la tarde voy al gimnasio", native: "In the afternoon I have gym" },
            { target: "Ceno en casa", native: "I have dinner at home" },
            { target: "Me acuesto temprano", native: "I sleep early" },
        ],
        "b-4-3": [
            { target: "¿Quieres salir el viernes?", native: "Do you want to go out Friday?" },
            { target: "¿Conoces algún lugar padre?", native: "Is there somewhere cool?" },
            { target: "¿A qué hora nos vemos?", native: "What time do we meet?" },
            { target: "¡Va, sale!", native: "Deal!" },
            { target: "Te escribo por WhatsApp", native: "I'll text you on WhatsApp" },
        ],

        // Intermediate

        "i-1-1": [
            { target: "Hoy me pasó algo chistoso", native: "Something funny happened today" },
            { target: "Estaba en medio de una junta cuando …", native: "I was in the middle of a meeting when …" },
            { target: "Al final todo salió bien", native: "In the end everything worked out" },
            { target: "Fue estresante pero valió la pena", native: "It was stressful but it was worth it" },
            { target: "¿Lo puedes creer?", native: "Can you believe that?" },
        ],
        "i-1-2": [
            { target: "Para mí, …", native: "For me, …" },
            { target: "Sinceramente, creo que …", native: "Honestly, I think that …" },
            { target: "No estoy seguro, pero …", native: "I'm not sure, but …" },
            { target: "La razón principal es …", native: "The main reason is …" },
            { target: "Mejor quedamos en que no estamos de acuerdo", native: "Let's agree to disagree" },
        ],
        "i-1-3": [
            { target: "Entiendo tu punto, pero …", native: "I see your point, but …" },
            { target: "Estoy de acuerdo hasta cierto punto", native: "I agree up to a point" },
            { target: "Desde mi perspectiva, …", native: "From my perspective, …" },
            { target: "¿No sería mejor …?", native: "Wouldn't it be better to …?" },
            { target: "Tiene sentido lo que dices", native: "What you're saying makes sense" },
        ],
        "i-2-1": [
            { target: "Disculpe, ¿puedo hablar con usted?", native: "Excuse me, can I speak with you?" },
            { target: "Hay un problema con …", native: "There's a problem with …" },
            { target: "¿Habrá manera de resolverlo?", native: "Is there any way to fix it?" },
            { target: "No estoy satisfecho", native: "I'm not satisfied" },
            { target: "Gracias por su atención", native: "Thanks for the attention" },
        ],
        "i-2-2": [
            { target: "Perdón por la tardanza", native: "Sorry I'm late" },
            { target: "Se me atravesó un imprevisto", native: "Something unexpected came up" },
            { target: "El tráfico estaba horrible", native: "The traffic was terrible" },
            { target: "No va a volver a pasar", native: "It won't happen again" },
            { target: "¿Cómo te lo puedo compensar?", native: "Can I make it up to you?" },
        ],
        "i-2-3": [
            { target: "Está un poco caro para mí", native: "It's a bit expensive for me" },
            { target: "¿Me lo deja en menos?", native: "Could you do it for less?" },
            { target: "Si llevo dos, ¿me hace descuento?", native: "If I take two, can I get a discount?" },
            { target: "¿Cuál es su mejor precio?", native: "What's the best price?" },
            { target: "Cerrado, me lo llevo", native: "Deal, I'll take it" },
        ],
        "i-3-1": [
            { target: "En cinco años, espero …", native: "In five years, I hope to …" },
            { target: "Mi plan es …", native: "My plan is …" },
            { target: "Estoy trabajando para …", native: "I'm working toward …" },
            { target: "Si todo sale bien, …", native: "If all goes well, …" },
            { target: "Todavía no estoy del todo seguro", native: "I'm not entirely sure yet" },
        ],
        "i-3-2": [
            { target: "Estoy trabajando en un proyecto que …", native: "I'm working on a project that …" },
            { target: "Mi rol es …", native: "My role is …" },
            { target: "La parte más difícil es …", native: "The hardest part is …" },
            { target: "He aprendido mucho con esto", native: "I've learned a lot from it" },
            { target: "El plazo está bien apretado", native: "The deadline is tight" },
        ],
        "i-3-3": [
            { target: "¿Te puedo dar una sugerencia?", native: "Can I give you a suggestion?" },
            { target: "Si yo fuera tú, …", native: "If I were you, …" },
            { target: "¿Ya pensaste en …?", native: "Have you thought about …?" },
            { target: "No seas tan duro contigo mismo", native: "Try not to be so hard on yourself" },
            { target: "Todo va a salir bien", native: "Everything will work out" },
        ],
        "i-4-1": [
            { target: "Allá en mi país, solemos …", native: "Back in my country, we usually …" },
            { target: "Aquí es bien diferente porque …", native: "Here it's quite different because …" },
            { target: "Una cosa que me llamó la atención fue …", native: "One thing that struck me was …" },
            { target: "Prefiero como lo hacen aquí", native: "I prefer the way it's done here" },
            { target: "Cada lugar tiene su encanto", native: "Every place has its charm" },
        ],
        "i-4-2": [
            { target: "Fue un viaje inolvidable", native: "It was an unforgettable trip" },
            { target: "Lo que más me marcó fue …", native: "What struck me most was …" },
            { target: "Conocí gente increíble", native: "I met amazing people" },
            { target: "Regresé siendo otra persona", native: "I came back a different person" },
            { target: "Lo recomiendo muchísimo", native: "I highly recommend it" },
        ],
        "i-4-3": [
            { target: "Tienes que ir a …", native: "You have to go to …" },
            { target: "Es un lugar que tiene una historia especial para mí", native: "It's a place with a special story for me" },
            { target: "Seguro te va a encantar", native: "You'll definitely like it" },
            { target: "Evita ir los fines de semana", native: "Avoid going on weekends" },
            { target: "Luego me cuentas qué te pareció", native: "Tell me later what you thought" },
        ],

        // Advanced

        "a-1-1": [
            { target: "En mi opinión, el trabajo remoto vale muchísimo más la pena", native: "In my opinion, remote work is much more worth it" },
            { target: "La oficina tiene sus ventajas, pero …", native: "The office has its advantages, but …" },
            { target: "No estoy de acuerdo justo por eso", native: "I disagree precisely because of that" },
            { target: "Se te está olvidando un detalle importante", native: "You're forgetting an important detail" },
            { target: "A fin de cuentas, depende mucho del tipo de trabajo", native: "At the end of the day, it depends a lot on the type of work" },
        ],
        "a-1-2": [
            { target: "Ya sé que la mayoría piensa lo contrario, pero …", native: "I know most people think otherwise, but …" },
            { target: "Siento que esto está mal entendido", native: "I think this is misunderstood" },
            { target: "El argumento de siempre en contra es …, pero …", native: "The standard argument against this is …, but …" },
            { target: "Sostengo esta opinión porque …", native: "I hold this opinion because …" },
            { target: "A lo mejor estoy equivocado, pero …", native: "I might even be wrong, but …" },
        ],
        "a-1-3": [
            { target: "Ahorita hay un debate enorme sobre …", native: "There's a huge debate going on about …" },
            { target: "Lo que está en juego es …", native: "What's at stake is …" },
            { target: "Yo me pongo del lado de …", native: "I side with …" },
            { target: "Es un tema complicado, no hay respuesta fácil", native: "It's a complex issue, there's no easy answer" },
            { target: "Esto divide opiniones hasta dentro de mi propia familia", native: "This divides opinions even within my family" },
        ],
        "a-2-1": [
            { target: "No vas a creer lo que pasó", native: "You won't believe what happened" },
            { target: "Todo empezó cuando …", native: "It all started when …" },
            { target: "Y entonces, de la nada, …", native: "Then, out of nowhere, …" },
            { target: "Para hacerte el cuento corto, …", native: "To cut a long story short, …" },
            { target: "Hasta la fecha me río cuando me acuerdo", native: "I still laugh when I remember this" },
        ],
        "a-2-2": [
            { target: "Antes de eso, yo pensaba que …", native: "Before this, I used to think that …" },
            { target: "Fue ahí cuando todo cambió", native: "That's when everything changed" },
            { target: "Aquello me hizo ver las cosas de otra manera", native: "That made me see things differently" },
            { target: "Hoy en día lo veo de una forma completamente distinta", native: "Nowadays, I see this in a completely different way" },
            { target: "Fue un parteaguas para mí", native: "It was a watershed moment for me" },
        ],
        "a-2-3": [
            { target: "Es de esos que se te quedan grabados mucho tiempo después", native: "It's one of those that sticks with you long after" },
            { target: "Lo que más me marcó fue …", native: "What struck me most was …" },
            { target: "Hay una escena en particular que vale toda la pena por sí sola", native: "There's one specific scene that's worth it on its own" },
            { target: "Te lo recomiendo a ojos cerrados", native: "I recommend it without hesitation" },
            { target: "¿Te hizo pensar en algo parecido en tu propia vida?", native: "Did it make you think of something similar in your own life?" },
        ],
        "a-3-1": [
            { target: "Resumiéndolo bien a la mala, …", native: "Putting it really roughly, …" },
            { target: "Para que te des una idea, …", native: "To give you an idea, …" },
            { target: "El día a día implica mucho …", native: "The day-to-day involves a lot of …" },
            { target: "La parte más difícil es, sin duda, …", native: "The hardest part is, without a doubt, …" },
            { target: "¿Tiene sentido lo que te estoy explicando?", native: "Does what I'm explaining make sense?" },
        ],
        "a-3-2": [
            { target: "Mira, déjame platicarte por qué esto tiene todo el sentido justo ahora", native: "Look, let me tell you why this makes sense right now" },
            { target: "Lo que nos diferencia es …", native: "What sets us apart is …" },
            { target: "¿Por qué yo? Porque viví este problema en carne propia", native: "Why me? Because I've lived this problem firsthand" },
            { target: "Le creo mucho a esto porque …", native: "I really believe in this because …" },
            { target: "Te apuesto que mucha gente necesita justo esto", native: "I bet a lot of people need exactly this" },
        ],
        "a-3-3": [
            { target: "Entiendo tu punto, pero te voy a contradecir", native: "I understand your point, but I'm going to disagree" },
            { target: "Tienes razón en parte, sin embargo …", native: "You're partly right, however …" },
            { target: "¿Te puedo ofrecer otra perspectiva?", native: "Can I offer you another perspective?" },
            { target: "A lo mejor lo estamos viendo desde ángulos distintos", native: "Maybe we're looking at this from different angles" },
            { target: "En el fondo, creo que queremos lo mismo, nada más que por caminos distintos", native: "Deep down, I think we want the same thing, just by different paths" },
        ],
        "a-4-1": [
            { target: "Una diferencia que me llama la atención es …", native: "One difference that strikes me is …" },
            { target: "Allá en mi país solemos …, mientras que aquí …", native: "Back in my country, we tend to …, while here …" },
            { target: "Cada cultura tiene su forma de lidiar con esto", native: "Each culture has its own way of dealing with this" },
            { target: "Siento que podríamos aprender mucho de …", native: "I think we could learn a lot from …" },
            { target: "No es mejor ni peor, es diferente", native: "It's not better or worse, it's different" },
        ],
        "a-4-2": [
            { target: "Una cosa que ha cambiado un montón es …", native: "One thing that's changed a lot is …" },
            { target: "Antes era de una forma, ahora es completamente distinto", native: "It used to be one way, now it's completely different" },
            { target: "No sé si sea para bien o para mal", native: "I don't know if it's for better or worse" },
            { target: "Esto refleja un cambio más grande en la sociedad", native: "This reflects a bigger shift in society" },
            { target: "Siento que estamos viviendo un momento de transición", native: "I feel like we're living through a moment of transition" },
        ],
        "a-4-3": [
            { target: "Lo que más consumo en este momento es …", native: "What I consume most right now is …" },
            { target: "Creo que esto dice mucho de mí porque …", native: "I think this says a lot about me because …" },
            { target: "No aguanto mucho tiempo sin …", native: "I can't go too long without …" },
            { target: "Trato de equilibrar contenido ligero con cosas más densas", native: "I try to balance lighter content with denser stuff" },
            { target: "¿Me das alguna recomendación?", native: "Got any recommendations for me?" },
        ],
}
