// Auto-converted from iOS WalkieTalkie/Models/LessonContent_French.swift.
// Update the iOS source first, then re-run the conversion script. See
// LessonCatalog for the lookup pipeline.

import type { LessonPhrase } from '../types'

export const frenchPhrases: Record<string, LessonPhrase[]> = {


        // First Timer

        "ft-1-1": [
            { target: "Salut !", native: "Hi!" },
            { target: "Bonjour, ça va ?", native: "Hello, how are you?" },
            { target: "Ça va bien, et toi ?", native: "I'm good, and you?" },
            { target: "Bonjour", native: "Good morning" },
            { target: "Bonsoir", native: "Good evening / Goodnight" },
        ],
        "ft-1-2": [
            { target: "Je m'appelle …", native: "My name is …" },
            { target: "Enchanté de te rencontrer", native: "Nice to meet you" },
            { target: "Comment tu t'appelles ?", native: "What's your name?" },
            { target: "Je viens des États-Unis", native: "I'm from the United States" },
            { target: "Tu es d'ici ?", native: "Are you from here?" },
        ],
        "ft-1-3": [
            { target: "J'habite à …", native: "I live in …" },
            { target: "Je viens de …", native: "I'm from …" },
            { target: "C'est une grande ville", native: "It's a big city" },
            { target: "C'est près de …", native: "It's near …" },
            { target: "Tu y es déjà allé ?", native: "Have you been there?" },
        ],
        "ft-2-1": [
            { target: "Un café, s'il te plaît", native: "A coffee, please" },
            { target: "Avec du lait", native: "With milk" },
            { target: "À emporter", native: "To go" },
            { target: "Ça coûte combien ?", native: "How much is it?" },
            { target: "Merci", native: "Thank you" },
        ],
        "ft-2-2": [
            { target: "Ça coûte combien, ça ?", native: "How much is this?" },
            { target: "C'est trop cher", native: "It's too expensive" },
            { target: "Vous prenez la carte ?", native: "Do you take card?" },
            { target: "En espèces", native: "In cash" },
            { target: "Je peux avoir le reçu ?", native: "Can I get the receipt?" },
        ],
        "ft-2-3": [
            { target: "Merci beaucoup", native: "Thanks a lot" },
            { target: "De rien", native: "You're welcome" },
            { target: "À bientôt", native: "See you soon" },
            { target: "Salut", native: "Bye" },
            { target: "C'était un plaisir", native: "It was a pleasure" },
        ],
        "ft-3-1": [
            { target: "À l'aéroport, s'il vous plaît", native: "To the airport, please" },
            { target: "Ça prend combien de temps ?", native: "How long does it take?" },
            { target: "Vous pouvez aller moins vite ?", native: "Can you slow down?" },
            { target: "C'est bon ici", native: "Here is fine" },
            { target: "Je vous dois combien ?", native: "How much do I owe you?" },
        ],
        "ft-3-2": [
            { target: "Comment je vais au … ?", native: "How do I get to the …?" },
            { target: "C'est loin d'ici ?", native: "Is it far from here?" },
            { target: "Tournez à gauche", native: "Turn left" },
            { target: "Allez tout droit", native: "Go straight" },
            { target: "Merci pour votre aide", native: "Thanks for your help" },
        ],
        "ft-3-3": [
            { target: "Je n'ai pas compris", native: "I didn't understand" },
            { target: "Tu peux répéter ?", native: "Can you repeat?" },
            { target: "Moins vite, s'il te plaît", native: "Slower, please" },
            { target: "Comment on dit … en français ?", native: "How do you say …?" },
            { target: "Tu parles anglais ?", native: "Do you speak English?" },
        ],
        "ft-4-1": [
            { target: "Enchanté", native: "Very nice to meet you" },
            { target: "Quelle belle maison", native: "What a beautiful home" },
            { target: "Merci pour l'invitation", native: "Thanks for the invitation" },
            { target: "Je peux aider ?", native: "Can I help?" },
            { target: "C'était délicieux", native: "It was delicious" },
        ],
        "ft-4-2": [
            { target: "Quel beau temps aujourd'hui", native: "What lovely weather today" },
            { target: "Tu es d'ici ?", native: "Are you from here?" },
            { target: "Ça te plaît, la France ?", native: "Are you enjoying it here?" },
            { target: "Qu'est-ce que tu fais dans la vie ?", native: "What do you do?" },
            { target: "À une prochaine", native: "See you around" },
        ],
        "ft-4-3": [
            { target: "Je travaille dans …", native: "I work in/with …" },
            { target: "Je suis … de métier", native: "I'm a … by profession" },
            { target: "Je travaille de chez moi", native: "I work from home" },
            { target: "J'adore ce que je fais", native: "I love what I do" },
            { target: "Et toi, tu fais quoi ?", native: "And you, what do you do?" },
        ],

        // Basic

        "b-1-1": [
            { target: "Je cherche un cadeau", native: "I'm looking for a gift" },
            { target: "C'est pour un ami", native: "It's for a friend" },
            { target: "Vous avez quelque chose de typique ?", native: "Do you have something typical?" },
            { target: "Combien coûte celui-là ?", native: "How much is that one?" },
            { target: "Je vais le prendre", native: "I'll take it" },
        ],
        "b-1-2": [
            { target: "Je peux l'essayer ?", native: "Can I try it on?" },
            { target: "Vous avez une autre taille ?", native: "Do you have another size?" },
            { target: "C'est un peu serré", native: "It's a bit tight" },
            { target: "J'adore cette couleur", native: "I love this color" },
            { target: "Ça me va bien ?", native: "Does it look good on me?" },
        ],
        "b-1-3": [
            { target: "Un kilo de tomates, s'il vous plaît", native: "A kilo of tomatoes, please" },
            { target: "Elles sont mûres ?", native: "Are they ripe?" },
            { target: "Vous pouvez choisir les meilleures ?", native: "Can you pick the best ones?" },
            { target: "C'est de saison ?", native: "Is it in season?" },
            { target: "Et avec ça ? Non, ce sera tout", native: "Anything else? No, that's it" },
        ],
        "b-2-1": [
            { target: "J'adore …", native: "I love …" },
            { target: "Je ne mange pas de viande", native: "I don't eat meat" },
            { target: "Je suis allergique au/à la …", native: "I'm allergic to …" },
            { target: "C'est quoi ton plat préféré ?", native: "What's your favorite dish?" },
            { target: "Tu cuisines ?", native: "Do you cook?" },
        ],
        "b-2-2": [
            { target: "Mon film préféré, c'est …", native: "My favorite movie is …" },
            { target: "Ça parle de …", native: "It's about …" },
            { target: "Tu l'as déjà vu ?", native: "Have you seen it?" },
            { target: "C'était vraiment émouvant", native: "It was really moving" },
            { target: "Je te le recommande", native: "I recommend it" },
        ],
        "b-2-3": [
            { target: "Pendant mon temps libre, je …", native: "In my free time I …" },
            { target: "Je fais ça depuis … ans", native: "I've been doing it for … years" },
            { target: "C'est très relaxant", native: "It's very relaxing" },
            { target: "Tu as un hobby ?", native: "Do you have any hobbies?" },
            { target: "Je peux t'apprendre", native: "I can teach you" },
        ],
        "b-3-1": [
            { target: "Ma famille habite à …", native: "My family lives in …" },
            { target: "Mes parents viennent de …", native: "My parents are from …" },
            { target: "J'ai un petit frère", native: "I have a younger brother" },
            { target: "Je les vois pendant les vacances", native: "I see them on holidays" },
            { target: "Ils me manquent", native: "I miss them" },
        ],
        "b-3-2": [
            { target: "On est quatre dans la famille", native: "There are four of us" },
            { target: "Mon frère est plus âgé", native: "My brother is older" },
            { target: "Ma mère est professeure", native: "My mom is a teacher" },
            { target: "On est très proches", native: "We're very close" },
            { target: "Tu as des photos ? Je peux voir ?", native: "Got photos? Can I see?" },
        ],
        "b-3-3": [
            { target: "Le week-end, on a l'habitude de …", native: "On weekends we usually …" },
            { target: "On dîne toujours ensemble", native: "We always eat dinner together" },
            { target: "On fête Noël", native: "We celebrate at Christmas" },
            { target: "C'est ma grand-mère qui cuisine", native: "My grandma cooks the food" },
            { target: "C'est une tradition de famille", native: "It's a family tradition" },
        ],
        "b-4-1": [
            { target: "J'arrive mardi", native: "I arrive on Tuesday" },
            { target: "Je reste une semaine", native: "I'm staying a week" },
            { target: "Je veux découvrir …", native: "I want to see …" },
            { target: "Qu'est-ce que tu recommandes ?", native: "What do you recommend?" },
            { target: "Je vais louer une voiture", native: "I'm renting a car" },
        ],
        "b-4-2": [
            { target: "Je me lève à sept heures", native: "I wake up at seven" },
            { target: "Je travaille jusqu'à dix-huit heures", native: "I work until six" },
            { target: "L'après-midi, je vais à la salle", native: "In the afternoon I have gym" },
            { target: "Je dîne à la maison", native: "I have dinner at home" },
            { target: "Je me couche tôt", native: "I sleep early" },
        ],
        "b-4-3": [
            { target: "Tu veux sortir vendredi ?", native: "Do you want to go out Friday?" },
            { target: "Tu connais un endroit sympa ?", native: "Is there somewhere cool?" },
            { target: "On se retrouve à quelle heure ?", native: "What time do we meet?" },
            { target: "C'est noté !", native: "Deal!" },
            { target: "Je t'envoie un message", native: "I'll text you on WhatsApp" },
        ],

        // Intermediate

        "i-1-1": [
            { target: "Il m'est arrivé un truc marrant aujourd'hui", native: "Something funny happened today" },
            { target: "J'étais en pleine réunion quand …", native: "I was in the middle of a meeting when …" },
            { target: "Au final, ça s'est bien passé", native: "In the end everything worked out" },
            { target: "C'était stressant mais ça valait le coup", native: "It was stressful but it was worth it" },
            { target: "Tu y crois, toi ?", native: "Can you believe that?" },
        ],
        "i-1-2": [
            { target: "Pour moi, …", native: "For me, …" },
            { target: "Honnêtement, je trouve que …", native: "Honestly, I think that …" },
            { target: "Je ne suis pas sûr, mais …", native: "I'm not sure, but …" },
            { target: "La raison principale, c'est …", native: "The main reason is …" },
            { target: "On va dire qu'on n'est pas d'accord", native: "Let's agree to disagree" },
        ],
        "i-1-3": [
            { target: "Je comprends ton point de vue, mais …", native: "I see your point, but …" },
            { target: "Je suis d'accord jusqu'à un certain point", native: "I agree up to a point" },
            { target: "De mon point de vue, …", native: "From my perspective, …" },
            { target: "Ce ne serait pas mieux de … ?", native: "Wouldn't it be better to …?" },
            { target: "Ce que tu dis a du sens", native: "What you're saying makes sense" },
        ],
        "i-2-1": [
            { target: "Excusez-moi, je peux vous parler ?", native: "Excuse me, can I speak with you?" },
            { target: "Il y a un problème avec …", native: "There's a problem with …" },
            { target: "Il y a moyen d'arranger ça ?", native: "Is there any way to fix it?" },
            { target: "Je ne suis pas satisfait", native: "I'm not satisfied" },
            { target: "Merci de votre attention", native: "Thanks for the attention" },
        ],
        "i-2-2": [
            { target: "Désolé pour le retard", native: "Sorry I'm late" },
            { target: "Il y a eu un imprévu", native: "Something unexpected came up" },
            { target: "Il y avait une circulation horrible", native: "The traffic was terrible" },
            { target: "Ça ne se reproduira pas", native: "It won't happen again" },
            { target: "Je peux me rattraper d'une façon ou d'une autre ?", native: "Can I make it up to you?" },
        ],
        "i-2-3": [
            { target: "C'est un peu cher pour moi", native: "It's a bit expensive for me" },
            { target: "Vous pouvez faire un effort ?", native: "Could you do it for less?" },
            { target: "Si j'en prends deux, vous me faites un prix ?", native: "If I take two, can I get a discount?" },
            { target: "C'est quoi votre meilleur prix ?", native: "What's the best price?" },
            { target: "Marché conclu, je le prends", native: "Deal, I'll take it" },
        ],
        "i-3-1": [
            { target: "Dans cinq ans, j'espère …", native: "In five years, I hope to …" },
            { target: "Mon plan, c'est de …", native: "My plan is …" },
            { target: "Je travaille pour …", native: "I'm working toward …" },
            { target: "Si tout se passe bien, …", native: "If all goes well, …" },
            { target: "Je ne sais pas encore vraiment", native: "I'm not entirely sure yet" },
        ],
        "i-3-2": [
            { target: "Je travaille sur un projet qui …", native: "I'm working on a project that …" },
            { target: "Mon rôle, c'est …", native: "My role is …" },
            { target: "Le plus dur, c'est …", native: "The hardest part is …" },
            { target: "J'ai beaucoup appris grâce à ça", native: "I've learned a lot from it" },
            { target: "Les délais sont serrés", native: "The deadline is tight" },
        ],
        "i-3-3": [
            { target: "Je peux te donner un conseil ?", native: "Can I give you a suggestion?" },
            { target: "Si j'étais toi, …", native: "If I were you, …" },
            { target: "Tu as déjà pensé à … ?", native: "Have you thought about …?" },
            { target: "Essaie de ne pas être trop dur avec toi-même", native: "Try not to be so hard on yourself" },
            { target: "Tout va bien se passer", native: "Everything will work out" },
        ],
        "i-4-1": [
            { target: "Chez moi, on a l'habitude de …", native: "Back in my country, we usually …" },
            { target: "Ici, c'est assez différent parce que …", native: "Here it's quite different because …" },
            { target: "Une chose qui m'a marqué, c'est …", native: "One thing that struck me was …" },
            { target: "Je préfère la façon de faire d'ici", native: "I prefer the way it's done here" },
            { target: "Chaque endroit a son charme", native: "Every place has its charm" },
        ],
        "i-4-2": [
            { target: "C'était un voyage inoubliable", native: "It was an unforgettable trip" },
            { target: "Ce qui m'a le plus marqué, c'est …", native: "What struck me most was …" },
            { target: "J'ai rencontré des gens incroyables", native: "I met amazing people" },
            { target: "Je suis revenu transformé", native: "I came back a different person" },
            { target: "Je le recommande vraiment", native: "I highly recommend it" },
        ],
        "i-4-3": [
            { target: "Il faut absolument que tu ailles à …", native: "You have to go to …" },
            { target: "C'est un endroit qui a une histoire spéciale pour moi", native: "It's a place with a special story for me" },
            { target: "Tu vas adorer, c'est sûr", native: "You'll definitely like it" },
            { target: "Évite d'y aller le week-end", native: "Avoid going on weekends" },
            { target: "Tu me diras ce que tu en as pensé", native: "Tell me later what you thought" },
        ],

        // Advanced

        "a-1-1": [
            { target: "À mon avis, le télétravail en vaut largement la peine", native: "In my opinion, remote work is much more worth it" },
            { target: "Le bureau a ses avantages, mais …", native: "The office has its advantages, but …" },
            { target: "Je ne suis pas d'accord, justement pour ça", native: "I disagree precisely because of that" },
            { target: "Tu oublies un détail important", native: "You're forgetting an important detail" },
            { target: "Au bout du compte, ça dépend vraiment du type de travail", native: "At the end of the day, it depends a lot on the type of work" },
        ],
        "a-1-2": [
            { target: "Je sais que la plupart des gens pensent le contraire, mais …", native: "I know most people think otherwise, but …" },
            { target: "Je trouve que c'est mal compris", native: "I think this is misunderstood" },
            { target: "L'argument classique contre ça, c'est …, mais …", native: "The standard argument against this is …, but …" },
            { target: "Je défends cette opinion parce que …", native: "I hold this opinion because …" },
            { target: "Je me trompe peut-être, mais …", native: "I might even be wrong, but …" },
        ],
        "a-1-3": [
            { target: "En ce moment, il y a un énorme débat autour de …", native: "There's a huge debate going on about …" },
            { target: "Ce qui est en jeu, c'est …", native: "What's at stake is …" },
            { target: "Moi, je suis du côté de …", native: "I side with …" },
            { target: "C'est une question complexe, il n'y a pas de réponse facile", native: "It's a complex issue, there's no easy answer" },
            { target: "Ça divise les opinions, même au sein de ma famille", native: "This divides opinions even within my family" },
        ],
        "a-2-1": [
            { target: "Tu ne vas pas croire ce qui m'est arrivé", native: "You won't believe what happened" },
            { target: "Tout a commencé quand …", native: "It all started when …" },
            { target: "Et là, sans prévenir, …", native: "Then, out of nowhere, …" },
            { target: "Bref, pour faire court, …", native: "To cut a long story short, …" },
            { target: "Aujourd'hui encore, ça me fait rire quand j'y repense", native: "I still laugh when I remember this" },
        ],
        "a-2-2": [
            { target: "Avant ça, je pensais que …", native: "Before this, I used to think that …" },
            { target: "C'est là que tout a basculé", native: "That's when everything changed" },
            { target: "Ça m'a fait voir les choses autrement", native: "That made me see things differently" },
            { target: "Aujourd'hui, je vois ça d'une manière complètement différente", native: "Nowadays, I see this in a completely different way" },
            { target: "Ça a été un vrai tournant pour moi", native: "It was a watershed moment for me" },
        ],
        "a-2-3": [
            { target: "C'est de ceux qui te restent en tête longtemps après", native: "It's one of those that sticks with you long after" },
            { target: "Ce qui m'a le plus marqué, c'est …", native: "What struck me most was …" },
            { target: "Il y a une scène en particulier qui vaut le détour à elle seule", native: "There's one specific scene that's worth it on its own" },
            { target: "Je le recommande les yeux fermés", native: "I recommend it without hesitation" },
            { target: "Ça t'a fait penser à quelque chose de similaire dans ta vie ?", native: "Did it make you think of something similar in your own life?" },
        ],
        "a-3-1": [
            { target: "Pour résumer très grossièrement, …", native: "Putting it really roughly, …" },
            { target: "Pour te donner une idée, …", native: "To give you an idea, …" },
            { target: "Au quotidien, ça implique beaucoup de …", native: "The day-to-day involves a lot of …" },
            { target: "Le plus dur, sans hésitation, c'est …", native: "The hardest part is, without a doubt, …" },
            { target: "Ce que je t'explique, ça a du sens ?", native: "Does what I'm explaining make sense?" },
        ],
        "a-3-2": [
            { target: "Écoute, laisse-moi t'expliquer pourquoi ça a du sens en ce moment", native: "Look, let me tell you why this makes sense right now" },
            { target: "Ce qui nous distingue, c'est …", native: "What sets us apart is …" },
            { target: "Pourquoi moi ? Parce que j'ai vécu ce problème dans ma chair", native: "Why me? Because I've lived this problem firsthand" },
            { target: "J'y crois vraiment, parce que …", native: "I really believe in this because …" },
            { target: "Je parie que pas mal de gens ont exactement besoin de ça", native: "I bet a lot of people need exactly this" },
        ],
        "a-3-3": [
            { target: "Je comprends ton point de vue, mais je ne suis pas d'accord", native: "I understand your point, but I'm going to disagree" },
            { target: "Tu as raison en partie, cependant …", native: "You're partly right, however …" },
            { target: "Je peux te proposer une autre perspective ?", native: "Can I offer you another perspective?" },
            { target: "On regarde peut-être ça sous des angles différents", native: "Maybe we're looking at this from different angles" },
            { target: "Au fond, je crois qu'on veut la même chose, juste par des chemins différents", native: "Deep down, I think we want the same thing, just by different paths" },
        ],
        "a-4-1": [
            { target: "Une différence qui me frappe, c'est …", native: "One difference that strikes me is …" },
            { target: "Chez moi, on a tendance à …, alors qu'ici …", native: "Back in my country, we tend to …, while here …" },
            { target: "Chaque culture a sa façon de gérer ça", native: "Each culture has its own way of dealing with this" },
            { target: "Je pense qu'on aurait beaucoup à apprendre de …", native: "I think we could learn a lot from …" },
            { target: "Ce n'est ni mieux ni moins bien, c'est différent", native: "It's not better or worse, it's different" },
        ],
        "a-4-2": [
            { target: "Une chose qui a beaucoup changé, c'est …", native: "One thing that's changed a lot is …" },
            { target: "Avant, c'était d'une façon, maintenant c'est complètement différent", native: "It used to be one way, now it's completely different" },
            { target: "Je ne sais pas si c'est en mieux ou en pire", native: "I don't know if it's for better or worse" },
            { target: "Ça reflète un changement plus profond dans la société", native: "This reflects a bigger shift in society" },
            { target: "J'ai le sentiment qu'on vit un moment de transition", native: "I feel like we're living through a moment of transition" },
        ],
        "a-4-3": [
            { target: "Ce que je consomme le plus en ce moment, c'est …", native: "What I consume most right now is …" },
            { target: "Je crois que ça en dit long sur moi, parce que …", native: "I think this says a lot about me because …" },
            { target: "Je ne peux pas rester très longtemps sans …", native: "I can't go too long without …" },
            { target: "J'essaie d'équilibrer du contenu léger avec des choses plus denses", native: "I try to balance lighter content with denser stuff" },
            { target: "Tu as une recommandation à me donner ?", native: "Got any recommendations for me?" },
        ],
}
