// Auto-converted from iOS WalkieTalkie/Models/LessonContent_Italian.swift.
// Update the iOS source first, then re-run the conversion script. See
// LessonCatalog for the lookup pipeline.

import type { LessonPhrase } from '../types'

export const italianPhrases: Record<string, LessonPhrase[]> = {


        // First Timer

        "ft-1-1": [
            { target: "Ciao!", native: "Hi!" },
            { target: "Ciao, come stai?", native: "Hello, how are you?" },
            { target: "Bene, e tu?", native: "I'm good, and you?" },
            { target: "Buongiorno", native: "Good morning" },
            { target: "Buonasera", native: "Good evening / Goodnight" },
        ],
        "ft-1-2": [
            { target: "Mi chiamo …", native: "My name is …" },
            { target: "Piacere di conoscerti", native: "Nice to meet you" },
            { target: "Come ti chiami?", native: "What's your name?" },
            { target: "Vengo dagli Stati Uniti", native: "I'm from the United States" },
            { target: "Sei di qui?", native: "Are you from here?" },
        ],
        "ft-1-3": [
            { target: "Abito a …", native: "I live in …" },
            { target: "Sono di …", native: "I'm from …" },
            { target: "È una città grande", native: "It's a big city" },
            { target: "Si trova vicino a …", native: "It's near …" },
            { target: "Ci sei mai stato?", native: "Have you been there?" },
        ],
        "ft-2-1": [
            { target: "Un caffè, per favore", native: "A coffee, please" },
            { target: "Con il latte", native: "With milk" },
            { target: "Da portare via", native: "To go" },
            { target: "Quanto costa?", native: "How much is it?" },
            { target: "Grazie", native: "Thank you" },
        ],
        "ft-2-2": [
            { target: "Quanto costa questo?", native: "How much is this?" },
            { target: "È troppo caro", native: "It's too expensive" },
            { target: "Accettate la carta?", native: "Do you take card?" },
            { target: "In contanti", native: "In cash" },
            { target: "Mi può dare lo scontrino?", native: "Can I get the receipt?" },
        ],
        "ft-2-3": [
            { target: "Grazie mille", native: "Thanks a lot" },
            { target: "Prego", native: "You're welcome" },
            { target: "A presto", native: "See you soon" },
            { target: "Ciao", native: "Bye" },
            { target: "È stato un piacere", native: "It was a pleasure" },
        ],
        "ft-3-1": [
            { target: "All'aeroporto, per favore", native: "To the airport, please" },
            { target: "Quanto ci vuole?", native: "How long does it take?" },
            { target: "Può andare più piano?", native: "Can you slow down?" },
            { target: "Qui va bene", native: "Here is fine" },
            { target: "Quanto le devo?", native: "How much do I owe you?" },
        ],
        "ft-3-2": [
            { target: "Come arrivo a …?", native: "How do I get to the …?" },
            { target: "È lontano da qui?", native: "Is it far from here?" },
            { target: "Gira a sinistra", native: "Turn left" },
            { target: "Vai sempre dritto", native: "Go straight" },
            { target: "Grazie dell'aiuto", native: "Thanks for your help" },
        ],
        "ft-3-3": [
            { target: "Non ho capito", native: "I didn't understand" },
            { target: "Puoi ripetere?", native: "Can you repeat?" },
            { target: "Più piano, per favore", native: "Slower, please" },
            { target: "Come si dice … in italiano?", native: "How do you say …?" },
            { target: "Parli inglese?", native: "Do you speak English?" },
        ],
        "ft-4-1": [
            { target: "Molto piacere", native: "Very nice to meet you" },
            { target: "Che bella casa", native: "What a beautiful home" },
            { target: "Grazie dell'invito", native: "Thanks for the invitation" },
            { target: "Posso aiutare?", native: "Can I help?" },
            { target: "Era squisito", native: "It was delicious" },
        ],
        "ft-4-2": [
            { target: "Che bel tempo oggi", native: "What lovely weather today" },
            { target: "Sei di qui?", native: "Are you from here?" },
            { target: "Ti sta piacendo l'Italia?", native: "Are you enjoying it here?" },
            { target: "Che lavoro fai?", native: "What do you do?" },
            { target: "Ci vediamo in giro", native: "See you around" },
        ],
        "ft-4-3": [
            { target: "Lavoro nel campo di …", native: "I work in/with …" },
            { target: "Di professione faccio il …", native: "I'm a … by profession" },
            { target: "Lavoro da casa", native: "I work from home" },
            { target: "Adoro quello che faccio", native: "I love what I do" },
            { target: "E tu, di cosa ti occupi?", native: "And you, what do you do?" },
        ],

        // Basic

        "b-1-1": [
            { target: "Sto cercando un regalo", native: "I'm looking for a gift" },
            { target: "È per un amico", native: "It's for a friend" },
            { target: "Avete qualcosa di tipico?", native: "Do you have something typical?" },
            { target: "Quanto costa quello?", native: "How much is that one?" },
            { target: "Lo prendo", native: "I'll take it" },
        ],
        "b-1-2": [
            { target: "Posso provarlo?", native: "Can I try it on?" },
            { target: "Avete un'altra taglia?", native: "Do you have another size?" },
            { target: "Mi sta un po' stretto", native: "It's a bit tight" },
            { target: "Mi piace molto questo colore", native: "I love this color" },
            { target: "Mi sta bene?", native: "Does it look good on me?" },
        ],
        "b-1-3": [
            { target: "Un chilo di pomodori, per favore", native: "A kilo of tomatoes, please" },
            { target: "Sono maturi?", native: "Are they ripe?" },
            { target: "Mi sceglie i migliori?", native: "Can you pick the best ones?" },
            { target: "È di stagione?", native: "Is it in season?" },
            { target: "Altro? No, basta così", native: "Anything else? No, that's it" },
        ],
        "b-2-1": [
            { target: "Adoro …", native: "I love …" },
            { target: "Non mangio la carne", native: "I don't eat meat" },
            { target: "Sono allergico a …", native: "I'm allergic to …" },
            { target: "Qual è il tuo piatto preferito?", native: "What's your favorite dish?" },
            { target: "Tu cucini?", native: "Do you cook?" },
        ],
        "b-2-2": [
            { target: "Il mio film preferito è …", native: "My favorite movie is …" },
            { target: "Parla di …", native: "It's about …" },
            { target: "L'hai già visto?", native: "Have you seen it?" },
            { target: "È stato molto emozionante", native: "It was really moving" },
            { target: "Te lo consiglio", native: "I recommend it" },
        ],
        "b-2-3": [
            { target: "Nel tempo libero io …", native: "In my free time I …" },
            { target: "Lo faccio da … anni", native: "I've been doing it for … years" },
            { target: "È molto rilassante", native: "It's very relaxing" },
            { target: "Tu hai qualche hobby?", native: "Do you have any hobbies?" },
            { target: "Posso insegnarti", native: "I can teach you" },
        ],
        "b-3-1": [
            { target: "La mia famiglia vive a …", native: "My family lives in …" },
            { target: "I miei genitori sono di …", native: "My parents are from …" },
            { target: "Ho un fratello più piccolo", native: "I have a younger brother" },
            { target: "Li vedo durante le feste", native: "I see them on holidays" },
            { target: "Mi mancano", native: "I miss them" },
        ],
        "b-3-2": [
            { target: "Siamo in quattro in famiglia", native: "There are four of us" },
            { target: "Mio fratello è più grande", native: "My brother is older" },
            { target: "Mia mamma fa la maestra", native: "My mom is a teacher" },
            { target: "Siamo molto uniti", native: "We're very close" },
            { target: "Hai delle foto? Posso vederle?", native: "Got photos? Can I see?" },
        ],
        "b-3-3": [
            { target: "Nei weekend di solito …", native: "On weekends we usually …" },
            { target: "Ceniamo sempre insieme", native: "We always eat dinner together" },
            { target: "Festeggiamo a Natale", native: "We celebrate at Christmas" },
            { target: "Mia nonna prepara il pranzo", native: "My grandma cooks the food" },
            { target: "È una tradizione di famiglia", native: "It's a family tradition" },
        ],
        "b-4-1": [
            { target: "Arrivo martedì", native: "I arrive on Tuesday" },
            { target: "Mi fermo una settimana", native: "I'm staying a week" },
            { target: "Voglio vedere …", native: "I want to see …" },
            { target: "Cosa mi consigli?", native: "What do you recommend?" },
            { target: "Noleggio una macchina", native: "I'm renting a car" },
        ],
        "b-4-2": [
            { target: "Mi sveglio alle sette", native: "I wake up at seven" },
            { target: "Lavoro fino alle sei", native: "I work until six" },
            { target: "Il pomeriggio vado in palestra", native: "In the afternoon I have gym" },
            { target: "Ceno a casa", native: "I have dinner at home" },
            { target: "Vado a dormire presto", native: "I sleep early" },
        ],
        "b-4-3": [
            { target: "Ti va di uscire venerdì?", native: "Do you want to go out Friday?" },
            { target: "Conosci qualche posto carino?", native: "Is there somewhere cool?" },
            { target: "A che ora ci vediamo?", native: "What time do we meet?" },
            { target: "Affare fatto!", native: "Deal!" },
            { target: "Ti scrivo su WhatsApp", native: "I'll text you on WhatsApp" },
        ],

        // Intermediate

        "i-1-1": [
            { target: "Oggi è successa una cosa divertente", native: "Something funny happened today" },
            { target: "Ero nel mezzo di una riunione quando …", native: "I was in the middle of a meeting when …" },
            { target: "Alla fine è andato tutto bene", native: "In the end everything worked out" },
            { target: "È stato stressante ma ne è valsa la pena", native: "It was stressful but it was worth it" },
            { target: "Ci credi?", native: "Can you believe that?" },
        ],
        "i-1-2": [
            { target: "Secondo me, …", native: "For me, …" },
            { target: "Sinceramente, penso che …", native: "Honestly, I think that …" },
            { target: "Non sono sicuro, però …", native: "I'm not sure, but …" },
            { target: "Il motivo principale è …", native: "The main reason is …" },
            { target: "Restiamo di idee diverse, va bene così", native: "Let's agree to disagree" },
        ],
        "i-1-3": [
            { target: "Capisco il tuo punto di vista, però …", native: "I see your point, but …" },
            { target: "Sono d'accordo fino a un certo punto", native: "I agree up to a point" },
            { target: "Dal mio punto di vista, …", native: "From my perspective, …" },
            { target: "Non sarebbe meglio …?", native: "Wouldn't it be better to …?" },
            { target: "Quello che dici ha senso", native: "What you're saying makes sense" },
        ],
        "i-2-1": [
            { target: "Scusi, posso parlare un attimo con lei?", native: "Excuse me, can I speak with you?" },
            { target: "C'è un problema con …", native: "There's a problem with …" },
            { target: "Si può fare qualcosa per risolverlo?", native: "Is there any way to fix it?" },
            { target: "Non sono soddisfatto", native: "I'm not satisfied" },
            { target: "Grazie per la disponibilità", native: "Thanks for the attention" },
        ],
        "i-2-2": [
            { target: "Scusa il ritardo", native: "Sorry I'm late" },
            { target: "È successo un imprevisto", native: "Something unexpected came up" },
            { target: "C'era un traffico terribile", native: "The traffic was terrible" },
            { target: "Non succederà più", native: "It won't happen again" },
            { target: "Posso rimediare in qualche modo?", native: "Can I make it up to you?" },
        ],
        "i-2-3": [
            { target: "È un po' caro per me", native: "It's a bit expensive for me" },
            { target: "Me lo fa a meno?", native: "Could you do it for less?" },
            { target: "Se ne prendo due, mi fa uno sconto?", native: "If I take two, can I get a discount?" },
            { target: "Qual è il miglior prezzo?", native: "What's the best price?" },
            { target: "Affare fatto, lo prendo", native: "Deal, I'll take it" },
        ],
        "i-3-1": [
            { target: "Tra cinque anni, spero di …", native: "In five years, I hope to …" },
            { target: "Il mio piano è …", native: "My plan is …" },
            { target: "Sto lavorando per …", native: "I'm working toward …" },
            { target: "Se va tutto bene, …", native: "If all goes well, …" },
            { target: "Non lo so ancora di preciso", native: "I'm not entirely sure yet" },
        ],
        "i-3-2": [
            { target: "Sto lavorando a un progetto che …", native: "I'm working on a project that …" },
            { target: "Il mio ruolo è …", native: "My role is …" },
            { target: "La parte più difficile è …", native: "The hardest part is …" },
            { target: "Ho imparato tanto da questo", native: "I've learned a lot from it" },
            { target: "La scadenza è stretta", native: "The deadline is tight" },
        ],
        "i-3-3": [
            { target: "Posso darti un consiglio?", native: "Can I give you a suggestion?" },
            { target: "Se fossi in te, …", native: "If I were you, …" },
            { target: "Hai mai pensato di …?", native: "Have you thought about …?" },
            { target: "Cerca di non essere troppo duro con te stesso", native: "Try not to be so hard on yourself" },
            { target: "Vedrai che andrà tutto bene", native: "Everything will work out" },
        ],
        "i-4-1": [
            { target: "Da noi, di solito si …", native: "Back in my country, we usually …" },
            { target: "Qui è molto diverso perché …", native: "Here it's quite different because …" },
            { target: "Una cosa che mi ha colpito è stata …", native: "One thing that struck me was …" },
            { target: "Preferisco come si fa qui", native: "I prefer the way it's done here" },
            { target: "Ogni posto ha il suo fascino", native: "Every place has its charm" },
        ],
        "i-4-2": [
            { target: "È stato un viaggio indimenticabile", native: "It was an unforgettable trip" },
            { target: "Quello che mi ha colpito di più è stato …", native: "What struck me most was …" },
            { target: "Ho conosciuto delle persone incredibili", native: "I met amazing people" },
            { target: "Sono tornato un'altra persona", native: "I came back a different person" },
            { target: "Lo consiglio davvero", native: "I highly recommend it" },
        ],
        "i-4-3": [
            { target: "Devi assolutamente andare a …", native: "You have to go to …" },
            { target: "È un posto che ha una storia speciale per me", native: "It's a place with a special story for me" },
            { target: "Ti piacerà di sicuro", native: "You'll definitely like it" },
            { target: "Evita di andarci nel weekend", native: "Avoid going on weekends" },
            { target: "Poi mi racconti che ne pensi", native: "Tell me later what you thought" },
        ],

        // Advanced

        "a-1-1": [
            { target: "Secondo me, lo smart working conviene molto di più", native: "In my opinion, remote work is much more worth it" },
            { target: "L'ufficio ha i suoi vantaggi, però …", native: "The office has its advantages, but …" },
            { target: "Non sono d'accordo proprio per questo motivo", native: "I disagree precisely because of that" },
            { target: "Ti stai dimenticando un dettaglio importante", native: "You're forgetting an important detail" },
            { target: "Alla fine dei conti, dipende molto dal tipo di lavoro", native: "At the end of the day, it depends a lot on the type of work" },
        ],
        "a-1-2": [
            { target: "Lo so che la maggior parte la pensa al contrario, però …", native: "I know most people think otherwise, but …" },
            { target: "Credo che sia una cosa fraintesa", native: "I think this is misunderstood" },
            { target: "L'obiezione classica è …, però …", native: "The standard argument against this is …, but …" },
            { target: "Sostengo questa opinione perché …", native: "I hold this opinion because …" },
            { target: "Magari mi sbaglio, però …", native: "I might even be wrong, but …" },
        ],
        "a-1-3": [
            { target: "In questo momento da noi c'è un dibattito enorme su …", native: "There's a huge debate going on about …" },
            { target: "Quello che è in gioco è …", native: "What's at stake is …" },
            { target: "Io sto dalla parte di …", native: "I side with …" },
            { target: "È una questione complessa, non c'è una risposta facile", native: "It's a complex issue, there's no easy answer" },
            { target: "Su questo si dividono perfino dentro la mia famiglia", native: "This divides opinions even within my family" },
        ],
        "a-2-1": [
            { target: "Non ci crederai a quello che è successo", native: "You won't believe what happened" },
            { target: "Allora, tutto è cominciato quando …", native: "It all started when …" },
            { target: "E lì, dal nulla, …", native: "Then, out of nowhere, …" },
            { target: "Per farla breve, …", native: "To cut a long story short, …" },
            { target: "Ancora oggi rido quando ci ripenso", native: "I still laugh when I remember this" },
        ],
        "a-2-2": [
            { target: "Prima di quel momento, pensavo che …", native: "Before this, I used to think that …" },
            { target: "È stato lì che è cambiato tutto", native: "That's when everything changed" },
            { target: "Quella cosa mi ha fatto vedere le cose in un altro modo", native: "That made me see things differently" },
            { target: "Oggi come oggi, la vedo in maniera completamente diversa", native: "Nowadays, I see this in a completely different way" },
            { target: "È stato uno spartiacque per me", native: "It was a watershed moment for me" },
        ],
        "a-2-3": [
            { target: "È uno di quelli che ti restano dentro a lungo", native: "It's one of those that sticks with you long after" },
            { target: "Quello che mi ha colpito di più è stato …", native: "What struck me most was …" },
            { target: "C'è una scena in particolare che da sola vale tutto", native: "There's one specific scene that's worth it on its own" },
            { target: "Te lo consiglio a occhi chiusi", native: "I recommend it without hesitation" },
            { target: "Ti ha fatto venire in mente qualcosa di simile nella tua vita?", native: "Did it make you think of something similar in your own life?" },
        ],
        "a-3-1": [
            { target: "Riassumendo molto grossolanamente, …", native: "Putting it really roughly, …" },
            { target: "Per farti un'idea, …", native: "To give you an idea, …" },
            { target: "Il quotidiano comporta molto …", native: "The day-to-day involves a lot of …" },
            { target: "La parte più difficile è, senza dubbio, …", native: "The hardest part is, without a doubt, …" },
            { target: "Ha senso quello che sto spiegando?", native: "Does what I'm explaining make sense?" },
        ],
        "a-3-2": [
            { target: "Allora, lascia che ti spieghi perché questa cosa ha senso proprio adesso", native: "Look, let me tell you why this makes sense right now" },
            { target: "Quello che ci distingue è …", native: "What sets us apart is …" },
            { target: "Perché io? Perché questo problema l'ho vissuto sulla mia pelle", native: "Why me? Because I've lived this problem firsthand" },
            { target: "Ci credo davvero perché …", native: "I really believe in this because …" },
            { target: "Scommetto che tante persone hanno bisogno proprio di questo", native: "I bet a lot of people need exactly this" },
        ],
        "a-3-3": [
            { target: "Capisco il tuo punto di vista, però mi permetto di dissentire", native: "I understand your point, but I'm going to disagree" },
            { target: "In parte hai ragione, però …", native: "You're partly right, however …" },
            { target: "Posso offrirti un'altra prospettiva?", native: "Can I offer you another perspective?" },
            { target: "Forse stiamo guardando la cosa da angolazioni diverse", native: "Maybe we're looking at this from different angles" },
            { target: "In fondo, credo che vogliamo la stessa cosa, solo per strade diverse", native: "Deep down, I think we want the same thing, just by different paths" },
        ],
        "a-4-1": [
            { target: "Una differenza che mi salta all'occhio è …", native: "One difference that strikes me is …" },
            { target: "Da noi si tende a …, mentre qui …", native: "Back in my country, we tend to …, while here …" },
            { target: "Ogni cultura ha il suo modo di affrontare questa cosa", native: "Each culture has its own way of dealing with this" },
            { target: "Credo che potremmo imparare molto da …", native: "I think we could learn a lot from …" },
            { target: "Non è meglio né peggio, è semplicemente diverso", native: "It's not better or worse, it's different" },
        ],
        "a-4-2": [
            { target: "Una cosa che è cambiata tantissimo è …", native: "One thing that's changed a lot is …" },
            { target: "Prima funzionava in un modo, adesso è completamente diverso", native: "It used to be one way, now it's completely different" },
            { target: "Non saprei dire se è in meglio o in peggio", native: "I don't know if it's for better or worse" },
            { target: "Questo riflette un cambiamento più ampio nella società", native: "This reflects a bigger shift in society" },
            { target: "Sento che stiamo vivendo un momento di transizione", native: "I feel like we're living through a moment of transition" },
        ],
        "a-4-3": [
            { target: "In questo periodo quello che consumo di più è …", native: "What I consume most right now is …" },
            { target: "Credo che dica parecchio di me perché …", native: "I think this says a lot about me because …" },
            { target: "Non riesco a stare troppo tempo senza …", native: "I can't go too long without …" },
            { target: "Cerco di bilanciare contenuti leggeri con cose più impegnative", native: "I try to balance lighter content with denser stuff" },
            { target: "Hai qualche consiglio da darmi?", native: "Got any recommendations for me?" },
        ],
}
